### ISSUE TITLE
Add Tests for Static Syntactic Checks

### ISSUE THREAD

**Issue by ddmills** [hridesh/panini#54]
The syntactic checks (issue #52) will need tests to confirm that they are working.

**Comment by dwtj** [comment]
We will not be able to test these syntactic checks using the same testing strategy that we have been for previous `proc` functionality. Previously, we have been running our annotation processor on *valid* capsule templates. Maven automatically informs us whenever one of the generated artifacts is malformed because of some bug in our `proc` code. This won't work when we *expect* some input capsule template to be invalid, because it will crash the entire Maven build.

I propose that we run `proc` tests (or at least those that we expect to fail) within JUnit tests which trigger `javac` to compile. Over the summer, I figured out how to run `javac` from within JUnit tests, so this is possible.

**Comment by dwtj** [comment]
Support for writing tests which only pass upon check failure have been added as of 3dc7ad0164dab240e1f72b9b1128fbd19f501ec1.

**Comment by dwtj** [comment]
Tests have been drafted for all current checks as of commit 730afc33bfb808701d168416adc6561c93756b93.
